---
- name:          The incredible pandemonium tests
  hosts:         pandama
  become:        true
  become_method: sudo
  become_user:   root
  tasks:
    - import_role:
        name:    pandemonium1986.init
    - import_role:
        name:    pandemonium1986.ansible
    - import_role:
        name:    pandemonium1986.ohmyzsh
    - import_role:
        name:    pandemonium1986.minikube
    - import_role:
        name:    pandemonium1986.kubectx
    - import_role:
        name:    pandemonium1986.k9s
    - import_role:
        name:    pandemonium1986.stern
    - import_role:
        name:    pandemonium1986.helm
