---
- name: The incredible pandemonium tests
  hosts: pandama
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - vars/init.yml
    - vars/ohmyzsh.yml
    - vars/pip.yml
  tasks:
    - name: "Import pandemonium1986 init role"
      ansible.builtin.import_role:
        name: pandemonium1986.init

    - name: "Import pandemonium1986 ohmyzsh role"
      ansible.builtin.import_role:
        name: pandemonium1986.ohmyzsh

    - name: "Import pandemonium1986 pip role"
      ansible.builtin.import_role:
        name: pandemonium1986.pip

    - name: "Import pandemonium1986.k8s_toolbox kubectl role"
      ansible.builtin.import_role:
        name: pandemonium1986.k8s_toolbox.kubectl

    - name: "Import pandemonium1986.k8s_toolbox kubectx role"
      ansible.builtin.import_role:
        name: pandemonium1986.k8s_toolbox.kubectx

    - name: "Import pandemonium1986.k8s_toolbox ink9sit role"
      ansible.builtin.import_role:
        name: pandemonium1986.k8s_toolbox.k9s

    - name: "Import pandemonium1986.k8s_toolbox minikube role"
      ansible.builtin.import_role:
        name: pandemonium1986.k8s_toolbox.minikube

    - name: "Import pandemonium1986.k8s_toolbox stern role"
      ansible.builtin.import_role:
        name: pandemonium1986.k8s_toolbox.stern
