---
- name:          The incredible pandemonium tests
  hosts:         pandama
  become:        true
  become_method: sudo
  become_user:   root
  collections:
    - pandemonium1986.k8s_toolbox
  tasks:
    - import_role:
        name:    pandemonium1986.init
    - import_role:
        name:    pandemonium1986.ansible
    - import_role:
        name:    pandemonium1986.ohmyzsh
    - import_role:
        name:    minikube
    - import_role:
        name:    kubectx
    - import_role:
        name:    k9s
    - import_role:
        name:    stern
    - import_role:
        name:    helm
