---
roles:
  - name: pandemonium1986.init
    version: "4.1.1"
  - name: pandemonium1986.ohmyzsh
    version: "4.1.0"
  - name: pandemonium1986.pip
    version: "4.1.0"

collections:
  - name: pandemonium1986.k8s_toolbox
    version: "2.3.0"
  - name: community.general
    version: "8.1.0"
